# Generated by Django 5.2.7 on 2025-11-18 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("approved", "已通过"),
                    ("rejected", "已拒绝"),
                ],
                default="pending",
                max_length=20,
                verbose_name="审核状态",
            ),
        ),
        migrations.CreateModel(
            name="SignRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.platform",
                        verbose_name="平台",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.rider",
                        verbose_name="骑手",
                    ),
                ),
            ],
            options={
                "verbose_name": "签约申请",
                "verbose_name_plural": "签约申请",
                "db_table": "sign_request",
                "unique_together": {("rider", "platform")},
            },
        ),
    ]
