# Generated by Django 5.2.7 on 2025-11-19 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discount", "0001_initial"),
        ("login", "0002_alter_enterrequest_status_signrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchantPlatformDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discount.discount",
                        verbose_name="折扣",
                    ),
                ),
                (
                    "merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.merchant",
                        verbose_name="商家",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.platform",
                        verbose_name="平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "商家平台折扣",
                "verbose_name_plural": "商家平台折扣",
                "db_table": "merchant_platform_discount",
                "unique_together": {("merchant", "platform")},
            },
        ),
    ]
