# Generated by Django 5.2.7 on 2025-11-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="打折比例"
                    ),
                ),
            ],
            options={
                "verbose_name": "折扣",
                "verbose_name_plural": "折扣",
                "db_table": "discount",
            },
        ),
    ]
