# Generated by Django 5.2.8 on 2025-12-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('login', '0005_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='login.platform', verbose_name='所属平台'),
        ),
    ]
