# Generated by Django 5.2.7 on 2025-11-19 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_alter_enterrequest_status_signrequest"),
        ("meal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="platform",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.platform",
                verbose_name="平台",
            ),
            preserve_default=False,
        ),
    ]
