# Generated by Django 5.2.8 on 2025-12-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0002_meal_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='rating_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
