# Generated by Django 5.2.8 on 2025-12-09 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unassigned', '未分配骑手'), ('assigned', '已分配骑手'), ('ready', '顾客待取餐'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('meal_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('platform_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rider_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='order.order')),
            ],
            options={
                'verbose_name': '订单评分',
                'verbose_name_plural': '订单评分',
                'db_table': 'order_rating',
            },
        ),
    ]
