# Generated by Django 5.2.8 on 2025-12-22 11:26

import django.db.models.deletion
from django.db import migrations, models


def migrate_order_items(apps, schema_editor):
    Order = apps.get_model('order', 'Order')
    OrderItem = apps.get_model('order', 'OrderItem')
    db_alias = schema_editor.connection.alias

    # 使用 values_list 避免加载关联对象
    order_rows = Order.objects.using(db_alias).all().values_list('id', 'meal_id', 'price')
    for order_id, meal_id, price in order_rows:
        if meal_id is None:
            continue
        OrderItem.objects.using(db_alias).create(
            order_id=order_id,
            meal_id=meal_id,
            quantity=1,
            unit_price=price,
            line_price=price,
        )


def migrate_order_meal_ratings(apps, schema_editor):
    OrderRating = apps.get_model('order', 'OrderRating')
    OrderItem = apps.get_model('order', 'OrderItem')
    OrderMealRating = apps.get_model('order', 'OrderMealRating')
    db_alias = schema_editor.connection.alias

    rating_rows = OrderRating.objects.using(db_alias).all().values_list('id', 'order_id', 'meal_rating')
    for rating_id, order_id, meal_rating in rating_rows:
        if meal_rating is None:
            continue
        items = OrderItem.objects.using(db_alias).filter(order_id=order_id).values_list('id', 'meal_id')
        for item_id, meal_id in items:
            OrderMealRating.objects.using(db_alias).create(
                order_id=order_id,
                order_item_id=item_id,
                meal_id=meal_id,
                rating=meal_rating,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_meal_rating_count_meal_rating_score'),
        ('order', '0002_alter_order_status_orderrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('line_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小计')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal', verbose_name='餐品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单餐品',
                'verbose_name_plural': '订单餐品',
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='OrderMealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='餐品评分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.meal', verbose_name='餐品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ratings', to='order.order', verbose_name='订单')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ratings', to='order.orderitem', verbose_name='订单餐品')),
            ],
            options={
                'verbose_name': '餐品评分',
                'verbose_name_plural': '餐品评分',
                'db_table': 'order_meal_rating',
            },
        ),
        migrations.RunPython(migrate_order_items, migrations.RunPython.noop),
        migrations.RunPython(migrate_order_meal_ratings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='orderrating',
            name='meal_rating',
        ),
    ]
